-- SE SitRep — initial schema
-- Paste into Supabase SQL Editor (Database -> SQL Editor -> New query).
-- Idempotent: safe to re-run.

-- ============================================================
-- Tables
-- ============================================================

-- profiles: 1:1 with Supabase Auth's auth.users table.
-- auth.users is managed by Supabase; we mirror the user id here
-- with our own profile fields.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text,
  avatar_url text,
  created_at timestamptz not null default now()
);

-- teams: the unit that members and standups belong to.
-- join_code is a 6-digit numeric code used to invite new members
-- (Life360-style). Auto-generated by a trigger below.
create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  join_code text not null unique,
  created_at timestamptz not null default now()
);
-- For schemas that pre-date join_code, add the column if missing.
alter table public.teams
  add column if not exists join_code text;

-- memberships: many-to-many between profiles and teams.
create table if not exists public.memberships (
  user_id uuid not null references public.profiles(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  role text not null default 'member'
    check (role in ('member', 'lead', 'manager')),
  joined_at timestamptz not null default now(),
  primary key (user_id, team_id)
);

-- ============================================================
-- Team join codes (Life360-style)
-- 6-digit numeric, permanent, unique. Auto-generated on insert.
-- Collisions retried until a free code is found (1M slot space).
-- ============================================================
create or replace function public.generate_join_code()
returns text
language plpgsql
set search_path = public
as $$
declare
  v_code text;
  v_exists boolean;
begin
  loop
    v_code := lpad(floor(random() * 1000000)::int::text, 6, '0');
    select exists(select 1 from public.teams where join_code = v_code)
      into v_exists;
    exit when not v_exists;
  end loop;
  return v_code;
end;
$$;

create or replace function public.set_team_join_code()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.join_code is null or new.join_code = '' then
    new.join_code := public.generate_join_code();
  end if;
  return new;
end;
$$;

drop trigger if exists before_insert_team_join_code on public.teams;
create trigger before_insert_team_join_code
  before insert on public.teams
  for each row execute function public.set_team_join_code();

-- Backfill: assign codes to any existing teams without one.
update public.teams
  set join_code = public.generate_join_code()
  where join_code is null or join_code = '';

-- Now that any pre-existing rows are filled, enforce not-null.
alter table public.teams
  alter column join_code set not null;

-- ============================================================
-- join_team_by_code(p_code text)
-- Atomic "look up team + insert membership" for the splash flow.
-- security definer bypasses RLS so users who aren't members yet
-- can still find a team by exact code match.
-- Raises 'invalid_join_code' if the code doesn't exist.
-- ============================================================
create or replace function public.join_team_by_code(p_code text)
returns public.teams
language plpgsql
security definer
set search_path = public
as $$
declare
  v_team public.teams;
begin
  select * into v_team from public.teams where join_code = p_code;
  if v_team.id is null then
    raise exception 'invalid_join_code' using errcode = 'P0001';
  end if;
  insert into public.memberships (user_id, team_id, role)
  values (auth.uid(), v_team.id, 'member')
  on conflict (user_id, team_id) do nothing;
  return v_team;
end;
$$;

-- ============================================================
-- create_team(p_name text)
-- Atomic "insert team + add creator as lead" for the splash flow.
-- security definer bypasses the team_member_read RLS gap that
-- prevented the creator from reading back their own freshly
-- inserted team. Raises 'team_name_blank' or 'team_name_too_long'
-- on bad input.
-- ============================================================
create or replace function public.create_team(p_name text)
returns public.teams
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(coalesce(p_name, ''));
  v_team public.teams;
begin
  if v_name = '' then
    raise exception 'team_name_blank' using errcode = 'P0001';
  end if;
  if char_length(v_name) > 80 then
    raise exception 'team_name_too_long' using errcode = 'P0001';
  end if;
  insert into public.teams (name) values (v_name) returning * into v_team;
  insert into public.memberships (user_id, team_id, role)
  values (auth.uid(), v_team.id, 'lead')
  on conflict (user_id, team_id) do nothing;
  return v_team;
end;
$$;

-- ============================================================
-- Auto-create a profile row when a new auth user signs up.
-- ============================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', new.email)
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- Row-Level Security
-- Default-deny: every new table needs explicit policies or
-- queries return empty for non-service-role callers.
-- ============================================================
alter table public.profiles    enable row level security;
alter table public.teams       enable row level security;
alter table public.memberships enable row level security;

-- ---- profiles ----------------------------------------------
-- A user can read their own profile.
drop policy if exists "profile_self_read" on public.profiles;
create policy "profile_self_read" on public.profiles
  for select using (auth.uid() = id);

-- A user can read profiles of teammates (shared team membership).
drop policy if exists "profile_teammate_read" on public.profiles;
create policy "profile_teammate_read" on public.profiles
  for select using (
    exists (
      select 1
      from public.memberships m1
      join public.memberships m2 on m1.team_id = m2.team_id
      where m1.user_id = auth.uid()
        and m2.user_id = profiles.id
    )
  );

-- A user can update their own profile.
drop policy if exists "profile_self_update" on public.profiles;
create policy "profile_self_update" on public.profiles
  for update using (auth.uid() = id);

-- ---- teams -------------------------------------------------
-- A user can read teams they belong to.
drop policy if exists "team_member_read" on public.teams;
create policy "team_member_read" on public.teams
  for select using (
    exists (
      select 1 from public.memberships
      where team_id = teams.id and user_id = auth.uid()
    )
  );

-- A user can create a team (and they'll add themselves as a member next).
drop policy if exists "team_authed_insert" on public.teams;
create policy "team_authed_insert" on public.teams
  for insert with check (auth.uid() is not null);

-- ---- memberships -------------------------------------------
-- A user can read their own memberships and those of their teammates.
drop policy if exists "membership_self_read" on public.memberships;
create policy "membership_self_read" on public.memberships
  for select using (
    user_id = auth.uid()
    or team_id in (
      select team_id from public.memberships where user_id = auth.uid()
    )
  );

-- A user can join a team they're inserting themselves into.
drop policy if exists "membership_self_insert" on public.memberships;
create policy "membership_self_insert" on public.memberships
  for insert with check (user_id = auth.uid());

-- ============================================================
-- Function security: lock down RPC surface
-- ============================================================
-- handle_new_user is trigger-only; revoking from client roles
-- removes the unintended /rest/v1/rpc/handle_new_user endpoint.
-- The trigger continues to fire regardless of EXECUTE grants.
revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- join_team_by_code must be callable by signed-in users (the whole point),
-- but not by anonymous clients.
revoke execute on function public.join_team_by_code(text) from public, anon;
grant  execute on function public.join_team_by_code(text) to authenticated;

-- create_team: same stance — authenticated only.
revoke execute on function public.create_team(text) from public, anon;
grant  execute on function public.create_team(text) to authenticated;

-- ============================================================
-- Team-scoped data: standups, blockers, comments, availability,
-- activity. All gated by current_user_team_ids() so RLS doesn't
-- recurse through the memberships policies.
-- ============================================================

-- ---------------- standups -----------------------------------
create table if not exists public.standups (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  day date not null default current_date,
  mood int check (mood is null or (mood >= 1 and mood <= 10)),
  yesterday text,
  today text,
  blockers_note text,
  cover_needed boolean not null default false,
  cover_note text,
  posted_at timestamptz not null default now(),
  unique (team_id, user_id, day)
);
create index if not exists standups_team_day_idx
  on public.standups (team_id, day desc);
create index if not exists standups_team_user_day_idx
  on public.standups (team_id, user_id, day desc);
alter table public.standups enable row level security;

drop policy if exists "standups_team_read" on public.standups;
create policy "standups_team_read" on public.standups
  for select using (team_id in (select public.current_user_team_ids()));
drop policy if exists "standups_self_insert" on public.standups;
create policy "standups_self_insert" on public.standups
  for insert with check (
    user_id = auth.uid()
    and team_id in (select public.current_user_team_ids())
  );
drop policy if exists "standups_self_update" on public.standups;
create policy "standups_self_update" on public.standups
  for update using (
    user_id = auth.uid()
    and team_id in (select public.current_user_team_ids())
  );
drop policy if exists "standups_self_delete" on public.standups;
create policy "standups_self_delete" on public.standups
  for delete using (
    user_id = auth.uid()
    and team_id in (select public.current_user_team_ids())
  );

-- ---------------- blockers -----------------------------------
create table if not exists public.blockers (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  title text not null,
  description text not null default '',
  severity text not null check (severity in ('critical','high','medium','low')),
  status text not null default 'open'
    check (status in ('open','in-progress','resolved')),
  owner_id uuid references public.profiles(id) on delete set null,
  category text check (category is null or category in ('ui','swe','backend')),
  start_date date,
  due_date date,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists blockers_team_status_idx
  on public.blockers (team_id, status);
alter table public.blockers enable row level security;

drop policy if exists "blockers_team_read" on public.blockers;
create policy "blockers_team_read" on public.blockers
  for select using (team_id in (select public.current_user_team_ids()));
drop policy if exists "blockers_team_insert" on public.blockers;
create policy "blockers_team_insert" on public.blockers
  for insert with check (
    team_id in (select public.current_user_team_ids())
    and (created_by is null or created_by = auth.uid())
  );
drop policy if exists "blockers_team_update" on public.blockers;
create policy "blockers_team_update" on public.blockers
  for update using (team_id in (select public.current_user_team_ids()));
drop policy if exists "blockers_team_delete" on public.blockers;
create policy "blockers_team_delete" on public.blockers
  for delete using (team_id in (select public.current_user_team_ids()));

-- ---------------- blocker_comments ---------------------------
create table if not exists public.blocker_comments (
  id uuid primary key default gen_random_uuid(),
  blocker_id uuid not null references public.blockers(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists blocker_comments_blocker_idx
  on public.blocker_comments (blocker_id, created_at);
alter table public.blocker_comments enable row level security;

drop policy if exists "blocker_comments_team_read" on public.blocker_comments;
create policy "blocker_comments_team_read" on public.blocker_comments
  for select using (
    exists (
      select 1 from public.blockers b
      where b.id = blocker_id
        and b.team_id in (select public.current_user_team_ids())
    )
  );
drop policy if exists "blocker_comments_self_insert" on public.blocker_comments;
create policy "blocker_comments_self_insert" on public.blocker_comments
  for insert with check (
    author_id = auth.uid()
    and exists (
      select 1 from public.blockers b
      where b.id = blocker_id
        and b.team_id in (select public.current_user_team_ids())
    )
  );

-- ---------------- slot_availability --------------------------
create table if not exists public.slot_availability (
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  slot_id text not null,
  is_available boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (team_id, user_id, slot_id)
);
alter table public.slot_availability enable row level security;

drop policy if exists "slot_availability_team_read" on public.slot_availability;
create policy "slot_availability_team_read" on public.slot_availability
  for select using (team_id in (select public.current_user_team_ids()));
drop policy if exists "slot_availability_self_upsert" on public.slot_availability;
create policy "slot_availability_self_upsert" on public.slot_availability
  for insert with check (
    user_id = auth.uid()
    and team_id in (select public.current_user_team_ids())
  );
drop policy if exists "slot_availability_self_update" on public.slot_availability;
create policy "slot_availability_self_update" on public.slot_availability
  for update using (
    user_id = auth.uid()
    and team_id in (select public.current_user_team_ids())
  );

-- ---------------- activity_events ----------------------------
create table if not exists public.activity_events (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('checkin','blocker','cover')),
  text text not null,
  created_at timestamptz not null default now()
);
create index if not exists activity_events_team_time_idx
  on public.activity_events (team_id, created_at desc);
alter table public.activity_events enable row level security;

drop policy if exists "activity_events_team_read" on public.activity_events;
create policy "activity_events_team_read" on public.activity_events
  for select using (team_id in (select public.current_user_team_ids()));
drop policy if exists "activity_events_self_insert" on public.activity_events;
create policy "activity_events_self_insert" on public.activity_events
  for insert with check (
    team_id in (select public.current_user_team_ids())
    and (user_id is null or user_id = auth.uid())
  );

-- ============================================================
-- Dev convenience
-- ============================================================
-- For local development, turn off email confirmation in
-- Supabase Dashboard -> Auth -> Providers -> Email
-- so sign-up immediately logs the user in. Re-enable for prod.
